### ISSUE TITLE
Tester Cart 

### ISSUE THREAD

**Issue by HippoPenguin** [ajavamind/rca-studio2#1]
The tester cart seems to run fine. But the first two stages of the test don't appear to be displaying correctly according to the images show in the maintenance manual.

**Comment by ajavamind** [comment]
You are correct , the test program is not displaying memory correctly because the emulation does not implement display of 1024 bytes of RAM. I have to investigate what code triggers higher resolution.

**Comment by ajavamind** [comment]
Fixed.
